### ISSUE TITLE
[ISSUE] Encountering errors while executing the "npm run build" command on a Linux system

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#66]
While executing the command "npm run build" the following errors are seen

ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts
57:46-83
[tsl] ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts(57,47)
      TS2307: Cannot find module '../../source/components/gitlabUtils' or its corresponding type declarations.

ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts
58:28-58
[tsl] ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts(58,29)
      TS2307: Cannot find module '../../source/components/user' or its corresponding type declarations.

ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts
62:32-64
[tsl] ERROR in /home/sravyam/meta_workspace/threshold/preprocess/folderStructureCheck.ts(62,33)
      TS2307: Cannot find module '../../source/components/global' or its corresponding type declarations.

ERROR in /home/sravyam/meta_workspace/threshold/preprocess/main.ts
38:42-74
[tsl] ERROR in /home/sravyam/meta_workspace/threshold/preprocess/main.ts(38,43)
      TS2307: Cannot find module '../../source/components/global' or its corresponding type declarations.

**To Reproduce**
Cloned the project using the command git clone from readme
git clone --recurse-submodules https://github.com/EasyEyes/threshold.git

Run the below npm commands
npm install
npm run build

**Expected behavior**
npm run build to execute without any errors

**Screenshots**
![error](https://user-images.githubusercontent.com/117389237/221022819-6593c6a3-30ad-422b-b1cd-7c22cdee89b1.jpeg)

**Desktop**
- OS: linux

**Comment by peilingjiang** [comment]
Hi @sravyam28, thanks for pointing that out. We have fixed it. Please try `git pull` for the latest version, and build again. We have also updated some dependency versions, so `npm install` would also be good.

**Comment by sravyam28** [comment]
Thanks @peilingjiang for quickly fixing the issue. I do still see an error in gitlabUtils file as shown below. As specified I did run npm install command again before npm run start
![Screenshot from 2023-02-27 10-16-19](https://user-images.githubusercontent.com/117389237/221649568-ffca7c66-ab36-48c1-b5c9-26b73b4d5a5c.png)

**Comment by peilingjiang** [comment]
Oh, thanks a lot for pointing it out! I'm sure it's well fixed now! Please let me know if there are any other problems.

**Comment by sravyam28** [comment]
Thanks @peilingjiang. I see the issue is now fully resolved.
